KORERO.Elements = (function () {
  'use strict';

  function init() {
    KORERO.Elements.Template = document.getElementById('core-app');
    KORERO.Elements.Loader = document.getElementById('showbox');
    KORERO.Actions = {
      SET_INTERFACE_ID: "SET_INTERFACE_ID",

      SET_SELECTION: "SET_SELECTION",

      CLOSE_BOTTOM: "CLOSE_BOTTOM",
      SET_DISCUSSION_TIME: "SET_DISCUSSION_TIME",
      SET_COMMENT_TIME: "SET_COMMENT_TIME",

      // NEW DISCUSSION
      OPEN_CREATE_DISCUSSION: "OPEN_CREATE_DISCUSSION",
      CLOSE_CREATE_DISCUSSION: "CLOSE_CREATE_DISCUSSION",
      SET_NEW_DISCUSSION_LINKS: "SET_NEW_DISCUSSION_LINKS",
      CLOSE_DISCUSSION_TOOLBAR: "CLOSE_DISCUSSION_TOOLBAR",

      // DISCUSSION VIDEO
      SET_DISCUSSION_LINK_FLAG: "SET_DISCUSSION_LINK_FLAG",

      // COMMENT VIDEO
      SET_COMMENT_LINK_FLAG: "SET_COMMENT_LINK_FLAG",

      // START LINKING and LINKING EDIT
      SET_LINKING: "SET_LINKING",
      SET_LINKING_EDIT: "SET_LINKING_EDIT",
      SET_LINK_TAPPED: "SET_LINK_TAPPED",
      SET_LINK_TIME: "SET_LINK_TIME",
      SET_NEW_LINK_TIME: "SET_NEW_LINK_TIME",
      CANCEL_LINKING: "CANCEL_LINKING",

      SET_VIDEO: "SET_VIDEO",
      SET_DISCUSSION_ID: "SET_DISCUSSION_ID",
      SET_REFER_VIEW: "SET_REFER_VIEW",
      SET_SAVE_LINKING: "SET_SAVE_LINKING",
      SET_NEW_DISCUSSION_LINK_REFER: "SET_NEW_DISCUSSION_LINK_REFER"
    }
  }

  return {
    init: init
  };
}());
