KORERO.Elements = (function () {
  'use strict';

  function init() {
    KORERO.Elements.Template = document.getElementById('core-app');
    KORERO.Elements.Loader = document.getElementById('showbox');
    KORERO.Actions = {
      SET_INTERFACE_ID: "SET_INTERFACE_ID",
      SET_VIDEO: "SET_VIDEO",

      // EVENTS

      CHANGE_DISCUSSION_TIME: "CHANGE_DISCUSSION_TIME",
      CHANGE_COMMENT_TIME: "CHANGE_COMMENT_TIME",
      SAVE_LINKING: "SAVE_LINKING",
      CANCEL_LINKING: "CANCEL_LINKING",
      CLOSE_EDIT_ACTIVITY: "CLOSE_EDIT_ACTIVITY",
      CLOSE_THUMBNAIL: "CLOSE_THUMBNAIL",
      READY_EDIT_ACTIVITY: "READY_EDIT_ACTIVITY",

      EDIT_ACTIVITY: "EDIT_ACTIVITY",
      START_LINKING: "START_LINKING",
      OPEN_THUMBNAIL_BLOCK: "OPEN_THUMBNAIL_BLOCK",
      TAP_NODE: "TAP_NODE",
      SAVE_DISCUSSION: "SAVE_DISCUSSION",
      CANCEL_DISCUSSION: "CANCEL_DISCUSSION",
      NEW_DISCUSSION: "NEW_DISCUSSION",
      CLOSE_DISCUSSION: "CLOSE_DISCUSSION",
      OPEN_EDITOR_OPTIONS: "OPEN_EDITOR_OPTIONS"

    }
  }

  return {
    init: init
  };
}());
